services:
  auth:
    ports: !reset []
  catalogo:
    ports: !reset []
  pedidos:
    ports: !reset []
  pagos:
    ports: !reset []

  tests:
    command:
      - python
      - -m
      - pytest
      - test_health.py
      - -v
      - --junitxml=/results/pytest.xml
      - --html=/results/reporte-pruebas.html
      - --self-contained-html
      - -p
      - no:cacheprovider